<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KartuKeluargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kartukeluarga')->insert([
            [
                'no_kk' => '6310051411090001',
                'nik' => '6310050205790000',
                'kepala_keluarga' => 'Suwardi',
                'alamat' => 'Jl. Transmigrasi Rt.01 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sutrisno',
                'ibu' => 'Rohaniyah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310053103080001',
                'nik' => '6310051709720001',
                'kepala_keluarga' => 'Slamet Mulyanto',
                'alamat' => 'Jl. Transmigrasi Rt.01 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sukarno',
                'ibu' => 'Wartinah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052103080519',
                'nik' => '6310050109750001',
                'kepala_keluarga' => 'Edi Waspodo',
                'alamat' => 'Jl. Transmigrasi Rt.01 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Paijo',
                'ibu' => 'Tuminem',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052203080164',
                'nik' => '6310052707690001',
                'kepala_keluarga' => 'Mario',
                'alamat' => 'Jl. Transmigrasi Rt.01 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Jumadi',
                'ibu' => 'Sumarni',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050808120007',
                'nik' => '6310053006570002',
                'kepala_keluarga' => 'Pujiono',
                'alamat' => 'Jl. Transmigrasi Rt.01 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Suharto',
                'ibu' => 'Sutiyem',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310051008120003',
                'nik' => '6310005560740002',
                'kepala_keluarga' => 'Diyani',
                'alamat' => 'Jl. Transmigrasi Rt.02 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sarman',
                'ibu' => 'Lasmini',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050507080020',
                'nik' => '6310052512680004',
                'kepala_keluarga' => 'Budiyono',
                'alamat' => 'Jl. Transmigrasi Rt.02 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sumarno',
                'ibu' => 'Sutini',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052007230001',
                'nik' => '6310056007720002',
                'kepala_keluarga' => 'Sulastri',
                'alamat' => 'Jl. Transmigrasi Rt.02 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sukirman',
                'ibu' => 'Rukayah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310051509180001',
                'nik' => '6310052311950002',
                'kepala_keluarga' => 'Edi Purwanto',
                'alamat' => 'Jl. Transmigrasi Rt.02 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sunaryo',
                'ibu' => 'Rohani',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050103120169',
                'nik' => '6310050302770003',
                'kepala_keluarga' => 'Ngatmin',
                'alamat' => 'Jl. Transmigrasi Rt.02 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sutaryo',
                'ibu' => 'Murni',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052103080468',
                'nik' => '6310050202790001',
                'kepala_keluarga' => 'Ahmad Bunisman',
                'alamat' => 'Jl. Transmigrasi Rt.03 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sutaryo',
                'ibu' => 'Suminah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050904100003',
                'nik' => '6310051709870001',
                'kepala_keluarga' => 'Sapto Irwansyah',
                'alamat' => 'Jl. Transmigrasi Rt.03 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Mulyadi',
                'ibu' => 'Sarifah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052202100014',
                'nik' => '6310054107720097',
                'kepala_keluarga' => 'Rumini',
                'alamat' => 'Jl. Transmigrasi Rt.03 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sunarto',
                'ibu' => 'Wagini',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310051402180004',
                'nik' => '6310072602960002',
                'kepala_keluarga' => 'Prayitno',
                'alamat' => 'Jl. Transmigrasi Rt.03 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Kasiman',
                'ibu' => 'Rohani',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050103120242',
                'nik' => '6310050706830002',
                'kepala_keluarga' => 'M. Joni',
                'alamat' => 'Jl. Transmigrasi Rt.03 Rw.01',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Syamsul',
                'ibu' => 'Mardiyah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050902100002',
                'nik' => '6310052012700001',
                'kepala_keluarga' => 'Mastamin',
                'alamat' => 'Jl. Transmigrasi Rt.04 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Kasim',
                'ibu' => 'Umi Salamah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052901110004',
                'nik' => '6310051010850004',
                'kepala_keluarga' => 'Syahnawi',
                'alamat' => 'Jl. Transmigrasi Rt.04 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Syukur',
                'ibu' => 'Munah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052803080013',
                'nik' => '6310051007670002',
                'kepala_keluarga' => 'Salehudin',
                'alamat' => 'Jl. Transmigrasi Rt.04 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Marsuki',
                'ibu' => 'Sahriyah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310051311090003',
                'nik' => '6310050107680108',
                'kepala_keluarga' => 'Sulono',
                'alamat' => 'Jl. Transmigrasi Rt.04 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sutrisno',
                'ibu' => 'Martini',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050911090001',
                'nik' => '6310050107610045',
                'kepala_keluarga' => 'Supar',
                'alamat' => 'Jl. Transmigrasi Rt.04 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Marzuki',
                'ibu' => 'Painah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050507080014',
                'nik' => '6310053112790003',
                'kepala_keluarga' => 'Daliman',
                'alamat' => 'Jl. Transmigrasi Rt.05 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sariman',
                'ibu' => 'Wagini',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052203080008',
                'nik' => '6310051011810003',
                'kepala_keluarga' => 'Muhammad Khojen',
                'alamat' => 'Jl. Transmigrasi Rt.05 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Slamet',
                'ibu' => 'Minah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052103080559',
                'nik' => '6310051009680002',
                'kepala_keluarga' => 'Ngatemin',
                'alamat' => 'Jl. Transmigrasi Rt.05 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sujiman',
                'ibu' => 'Warti',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310052703080006',
                'nik' => '6310052804700001',
                'kepala_keluarga' => 'Sujadi',
                'alamat' => 'Jl. Transmigrasi Rt.05 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Sutiman',
                'ibu' => 'Rohmah',
                'tanggal_penerbitan' => '2023-01-01',
            ],
            [
                'no_kk' => '6310050507080026',
                'nik' => '6310050908670001',
                'kepala_keluarga' => 'Sunardi',
                'alamat' => 'Jl. Transmigrasi Rt.05 Rw.02',
                'kelurahan_desa' => 'Karang Sari',
                'kecamatan' => 'Kusan Hulu',
                'kabupaten' => 'Tanah Bumbu',
                'provinsi' => 'Kalimantan Selatan',
                'kode_pos' => '72272',
                'status_hubungan_dalam_keluarga' => 'Kepala Keluarga',
                'no_paspor' => '-',
                'no_kitas_kitap' => '-',
                'ayah' => 'Karto',
                'ibu' => 'Kasiyem',
                'tanggal_penerbitan' => '2023-01-01',
            ]
        ]);
    }
}
