<?php

namespace Database\Seeders;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('penduduk')->insert([
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 1,
                'nama' => 'Suwardi',
                'nik' => '6310050205790000',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1979-05-02',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.01 Rw.01 Desa Karanag Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 2,
                'nama' => 'Slamet Mulyanto',
                'nik' => '6310051709720001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1972-09-17',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.01 Rw.01 Desa Karang sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 3,
                'nama' => 'Edi Waspodo',
                'nik' => '6310050109750001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '1975-09-01',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.01 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 4,
                'nama' => 'Mario',
                'nik' => '6310052707690001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Banjar',
                'tanggal_lahir' => '1969-07-27',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.01 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 5,
                'nama' => 'Pujiono',
                'nik' => '6310053006570002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Banyuwangi',
                'tanggal_lahir' => '1957-06-30',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SDRJT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.01 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 6,
                'nama' => 'Diyani',
                'nik' => '6310005560740002',
                'jenis_kelamin' => 'Perempuan',
                'status_perkawinan' => 'Cerai',
                'tempat_lahir' => 'Madura',
                'tanggal_lahir' => '1940-07-16',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.02 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 7,
                'nama' => 'Budiyono',
                'nik' => '6310052512680004',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Sleman',
                'tanggal_lahir' => '1968-12-26',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'DIPLOMA IV/STRATA I',
                'pekerjaan' => 'PEGAWAI NEGERI SIPIL (PNS)',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.02 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 8,
                'nama' => 'Sulastri',
                'nik' => '6310056007720002',
                'jenis_kelamin' => 'Perempuan',
                'status_perkawinan' => 'Cerai Mati',
                'tempat_lahir' => 'Kulonprogo',
                'tanggal_lahir' => '1972-07-20',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'Mengurus Rumah Tangga',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.02 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 9,
                'nama' => 'Edi Purwanto',
                'nik' => '6310052311950002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Karang Sari',
                'tanggal_lahir' => '1995-11-23',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'Wiraswasta',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.02 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 10,
                'nama' => 'Ngatmin',
                'nik' => '6310050302770003',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Wonosobo',
                'tanggal_lahir' => '1977-02-03',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.02 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 11,
                'nama' => 'Ahmad Bunisman',
                'nik' => '6310050202790001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Jember',
                'tanggal_lahir' => '1979-02-02',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SDRJT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.03 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 12,
                'nama' => 'Sapto Irwansyah',
                'nik' => '6310051709870001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Pematang Ulin',
                'tanggal_lahir' => '1987-09-17',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/SEDERAJAT',
                'pekerjaan' => 'Wiraswasta',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.03 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 13,
                'nama' => 'Rumini',
                'nik' => '6310054107720097',
                'jenis_kelamin' => 'Perempuan',
                'status_perkawinan' => 'Cerai Mati',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1972-07-01',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SDRJT',
                'pekerjaan' => 'Mengurus Rumah Tangga',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.03 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 14,
                'nama' => 'Prayitno',
                'nik' => '6310072602960002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Rejowinangun',
                'tanggal_lahir' => '1996-07-26',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SLTP/SEDERAJAT',
                'pekerjaan' => 'Wiraswasta',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.03 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 15,
                'nama' => 'M. Joni',
                'nik' => '6310050706830002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Kota Baru',
                'tanggal_lahir' => '1983-06-07',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.03 Rw.01 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 16,
                'nama' => 'Mastamin',
                'nik' => '6310052012700001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Martapura',
                'tanggal_lahir' => '1970-12-20',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.04 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 17,
                'nama' => 'Syahnawi',
                'nik' => '6310051010850004',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Kandangan',
                'tanggal_lahir' => '1985-10-10',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.04 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 18,
                'nama' => 'Salehudin',
                'nik' => '6310051007670002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Batulicin',
                'tanggal_lahir' => '1967-07-10',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.04 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 19,
                'nama' => 'Sulono',
                'nik' => '6310050107680108',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Ponorogo',
                'tanggal_lahir' => '1968-07-01',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'WIRASWASTA',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.04 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 20,
                'nama' => 'Supar',
                'nik' => '6310050107610045',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Grobogan',
                'tanggal_lahir' => '1961-07-01',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.04 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 21,
                'nama' => 'Daliman',
                'nik' => '6310053112790003',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Kulon Progo',
                'tanggal_lahir' => '1979-12-31',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'DIPLOMA III',
                'pekerjaan' => 'PNS',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.05 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 22,
                'nama' => 'Muhammad Khojen',
                'nik' => '6310051011810003',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Nganjuk',
                'tanggal_lahir' => '1982-08-04',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'WIRASWASTA',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.05 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 23,
                'nama' => 'Ngatemin',
                'nik' => '6310051009680002',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Temanggung',
                'tanggal_lahir' => '1968-09-10',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.05 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 24,
                'nama' => 'Sujadi',
                'nik' => '6310052804700001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Blora',
                'tanggal_lahir' => '1970-04-28',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.05 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],
            [
                'desa_id' => 11,
                'kartukeluarga_id' => 25,
                'nama' => 'Sunardi',
                'nik' => '6310050908670001',
                'jenis_kelamin' => 'Laki-laki',
                'status_perkawinan' => 'Kawin',
                'tempat_lahir' => 'Jawa Tengah',
                'tanggal_lahir' => '1967-08-09',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'TAMAT SD/SEDERAJAT',
                'pekerjaan' => 'PETANI/PEKEBUN',
                'alamat_lengkap' => 'Jl. Transmigrasi Rt.05 Rw.02 Desa Karang Sari Kecamatan Kusan Hulu Kabupaten tanah Bumbu Kalimantan Selatan',
                'kedudukan_dalam_keluarga' => 'Kepala Keluarga',
                'warga_negara' => 'Indonesia',
            ],

            ]);
    }
}
